# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cprice', models.FloatField(default=0, verbose_name='总价')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=20, verbose_name='货物名称')),
                ('gprice', models.FloatField(verbose_name='货物价格')),
                ('gclassify', models.CharField(max_length=20, verbose_name='货物分类')),
                ('gtime', models.DateTimeField(verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('upassword', models.CharField(max_length=20, verbose_name='密码')),
                ('uicon', models.ImageField(upload_to='', verbose_name='用户头像')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='gbuyer',
            field=models.ManyToManyField(null=True, to='tradingApp.User'),
        ),
        migrations.AddField(
            model_name='buyercard',
            name='cbuyer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tradingApp.User'),
        ),
        migrations.AddField(
            model_name='buyercard',
            name='cbuyerGoods',
            field=models.ManyToManyField(to='tradingApp.Good'),
        ),
    ]
