# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-30 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradingApp', '0002_auto_20180627_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='无名氏', max_length=20)),
                ('contemt', models.TextField(max_length=250)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='good',
            name='gbuyer',
            field=models.ManyToManyField(to='tradingApp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='guser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradingApp.Good'),
        ),
    ]
