# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-30 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingApp', '0003_auto_20180630_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='gpicture',
            field=models.ImageField(default='/static/icon/1.jpg', upload_to=''),
        ),
    ]
