# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradingApp', '0004_good_gpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='good',
            name='gbuyer',
        ),
        migrations.AddField(
            model_name='user',
            name='uremainder',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='cart',
            name='goodId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tradingApp.Good'),
        ),
        migrations.AddField(
            model_name='cart',
            name='useId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tradingApp.User'),
        ),
    ]
