# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradingApp', '0005_auto_20180704_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='goodId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradingApp.Good'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='useId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tradingApp.User'),
        ),
    ]
