# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingApp', '0007_auto_20180704_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gnumber',
            field=models.IntegerField(default=0),
        ),
    ]
