# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-18 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingApp', '0008_cart_gnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyercard',
            name='cremainder',
            field=models.FloatField(default=1000, verbose_name='用户余额'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uremainder',
            field=models.FloatField(default=1000, verbose_name='用户余额'),
        ),
    ]
