# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-19 02:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradingApp', '0010_fuck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fuck',
        ),
    ]
